export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';

export const SAFETY_DATA = 'SAFETY_DATA';
export const SAFETY_FAILED = 'SAFETY_FAILED';
export const SAFETY_LOADING = 'SAFETY_LOADING';

export const FOQA_DATA = 'FOQA_DATA';
export const FOQA_FAILED = 'FOQA_FAILED';
export const FOQA_LOADING = 'FOQA_LOADING';

export const CC_DATA = 'CC_DATA';
export const CC_LOADING = 'CC_LOADING';
export const CC_FAILED = 'CC_FAILED';
export const INSERT_CC_ROW = 'INSERT_CC_ROW';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const EMS_LOGIN_REQUEST = 'EMS_LOGIN_REQUEST';
export const EMS_LOGIN_SUCCESS = 'EMS_LOGIN_SUCCESS';
export const EMS_LOGIN_FAILURE = 'EMS_LOGIN_FAILURE';

export const EMS_REQUEST_PARAMS = 'EMS_REQUEST_PARAMS';
export const EMS_GET_SUCCESS = 'EMS_GET_SUCCESS';
export const EMS_GET_FAILURE = 'EMS_GET_FAILURE';
export const EMS_POST_SUCCESS = 'EMS_POST_SUCCESS';
export const EMS_POST_FAILURE = 'EMS_POST_FAILURE';
export const EMS_AIRPORTS_SUCCESS = 'EMS_AIRPORTS_SUCCESS';
export const EMS_AIRPORTS_FAILURE = 'EMS_AIRPORTS_FAILURE';

